source 'https://rubygems.org'
gem 'sinatra', '>= 1.0'
gem 'rake'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'dm-constraints'
gem 'haml'
gem 'carrierwave'
gem 'carrierwave-datamapper'
gem 'rmagick'
group :test do
  gem 'rspec', :require => 'spec'
  gem 'rack-test'
end
